name: google_directions_api
version: 0.9.1
homepage: https://github.com/marchdev-tk/google_directions_api
description: The Directions API is a service that calculates directions between locations. You can search for directions for several modes of transportation.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  google_polyline_algorithm: ^3.1.0
  http: ^0.13.6
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  test: ^1.24.3
